### ISSUE TITLE
releasing new version to npm

### ISSUE THREAD

**Issue by sunkibaek** [ppsreejith/react-native-apps-flyer#17]
Hello,

First of all, thanks for the great package. We are using it in our production app and it works great!

Now that we have a couple of commits after `1.2.5` release do you guys mind releasing a new version please? I am in need of one of the patches committed after `1.2.5`

Thanks!

**Comment by ppsreejith** [comment]
I've published the next version which contains all these recent fixes. Thanks for pointing that out 👍
