### ISSUE TITLE
Android Module missing callbacks and event values 

### ISSUE THREAD

**Issue by maluramichael** [ppsreejith/react-native-apps-flyer#4]
Currently the android module does not fire callbacks on init and you cannot pass event values to the api.

**Comment by EmilScherdin** [comment]
@maluramichael Is this something that are going to be fixed soon? 😄

**Comment by mcabs3** [comment]
Is the android module working at all? I was able to get iOS working, but android won't send an event or init.

**Comment by mcabs3** [comment]
I created a PR that matched iOS and android uses.

**Comment by mcabs3** [comment]
@maluramichael This can be closed
