### ISSUE TITLE
u.default.sendTrackingWithEvent is not a function

### ISSUE THREAD

**Issue by devhyunjae** [ppsreejith/react-native-apps-flyer#8]
## Expected Behavior

```
import af from 'react-native-apps-flyer';
af.sendTrackingWithEvent('my event name', params, this.debug);
```

should work.
## Actual Behavior

raises error below.

```
2016-10-07 14:29:23.597796 惠首尔[821:381565] { [TypeError: u.default.sendTrackingWithEvent is not a function. (In 'u.default.sendTrackingWithEvent("af_complete_registration",e,this.debug)', 'u.default.sendTrackingWithEvent' is undefined)]
  line: 489,
  column: 449,
  sourceURL: 'file:///var/containers/Bundle/Application/5668D7BF-F98C-44BA-8DEE-75E625B81213/%E6%83%A0%E9%A6%96%E5%B0%94.app/main.jsbundle' }
```
## Reason

Since Version 1.1.1,  `.sendTrackingWithEvent` had exist, and i wrote my code like below.

```
import af from 'react-native-apps-flyer';
af.sendTrackingWithEvent('my event name', params, this.debug);
```

works fine.

Updated this lib package to 1.2.2, and `.sendTrackingWithEvent` has been replaced to `trackEvent`

ref: https://github.com/ppsreejith/react-native-apps-flyer/commit/b080657c428dae1797ce3f9f9c34175abb5a4fbf

and now the problem is, my code will throw this error, because it doesn't exist anymore.

```
2016-10-07 14:29:23.597796 惠首尔[821:381565] { [TypeError: u.default.sendTrackingWithEvent is not a function. (In 'u.default.sendTrackingWithEvent("af_complete_registration",e,this.debug)', 'u.default.sendTrackingWithEvent' is undefined)]
  line: 489,
  column: 449,
  sourceURL: 'file:///var/containers/Bundle/Application/5668D7BF-F98C-44BA-8DEE-75E625B81213/%E6%83%A0%E9%A6%96%E5%B0%94.app/main.jsbundle' }
```

Every lib user has to change their method call part, and that's a `BIG PROBLEM.`
## Solution

Maybe make it a alias method to allow both `sendTrackingWithEvent` and `trackEvent`?
I'm not sure about what the commiter's purpose is, but this needs to be fixed.

**Comment by mcabs3** [comment]
@devhyunjae that is a good point, I will add alias methods in my next PR. The reason why I decided to change them was for consistency between android and iOS really.

thanks for bringing this up, I will also make note of this in the realm

One question I have for you is do you want alias methods, but still keep the exact same functionality? or would you want the extended function for android with sendTrackingWithEvent? Meaning should I allow for passing a callback and such. Doing that would cause errors, but would allow you to continue to use the same method calls.

**Comment by mcabs3** [comment]
Created a PR with the old methods added back in, I will refactor to make them alias methods

https://github.com/ppsreejith/react-native-apps-flyer/pull/9
